apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-java
  namespace: ns-seratic-dev
  labels:
    app: demo-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: demo-java
        image: danielaaza1/demo_java:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: configmap-dev
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-java-service
  namespace: ns-seratic-dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb 
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:796632586984:certificate/e75b9544-5f48-41bd-9a1e-bdfcae52de7e
    service.beta.kubernetes.io/aws-load-balancer-tls-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: |
      APP=demo_java
  labels:
    app: demo-java
spec:
  type: NodePort
  selector:
    app: demo-java
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
